[variables]
NODE_VERSION = "20.11.0"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npm run start"

[providers]
nodejs = "20.11.0"